import React, { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import {
  FileText,
  Download,
  Loader2,
  Image,
  FileImage,
  CheckCircle,
  Settings,
  Grid
} from 'lucide-react';
import { toast } from 'sonner';

export default function PDFExportModal({ documents, isOpen, onClose }) {
  const [selectedPages, setSelectedPages] = useState([]);
  const [pdfQuality, setPdfQuality] = useState('standard');
  const [includeAllPages, setIncludeAllPages] = useState(true);
  const [combineDocuments, setCombineDocuments] = useState(documents.length > 1);
  const [isExporting, setIsExporting] = useState(false);
  const [includeExtractedText, setIncludeExtractedText] = useState(true);
  const [orientation, setOrientation] = useState('portrait');

  const totalPages = documents.reduce((sum, doc) => sum + (doc.page_count || 1), 0);

  const generatePDFMutation = useMutation({
    mutationFn: async (exportConfig) => {
      const response = await base44.integrations.Core.InvokeLLM({
        prompt: `Generate a professional PDF document with the following configuration:

Documents to include: ${exportConfig.documents.map(d => d.title).join(', ')}
Quality: ${exportConfig.quality}
Orientation: ${exportConfig.orientation}
Include text: ${exportConfig.includeText}

For each document, include:
1. Document title as header
2. ${exportConfig.includeText ? 'Extracted OCR text' : 'Document images only'}
3. Page numbers
4. Creation date
5. Tags (if any)

Format the PDF professionally with:
- Clear headers and footers
- Proper spacing
- Table of contents if multiple documents
- Watermark with "Generated by Helper33 Workspace" in footer

Return the PDF as a downloadable file.`,
        file_urls: exportConfig.imageUrls,
        response_json_schema: {
          type: "object",
          properties: {
            pdf_content: { type: "string" },
            page_count: { type: "number" },
            file_size_kb: { type: "number" }
          }
        }
      });

      return response;
    }
  });

  const handleExport = async () => {
    setIsExporting(true);

    try {
      // Collect all image URLs based on selection
      const imageUrls = [];
      const docTitles = [];

      documents.forEach(doc => {
        if (includeAllPages || selectedPages.includes(doc.id)) {
          const urls = doc.processed_image_urls || doc.original_image_urls || [];
          imageUrls.push(...urls);
          docTitles.push(doc.title);
        }
      });

      if (imageUrls.length === 0) {
        toast.error('No pages selected for export');
        setIsExporting(false);
        return;
      }

      // For single document with existing PDF
      if (documents.length === 1 && documents[0].pdf_url && includeAllPages) {
        window.open(documents[0].pdf_url, '_blank');
        toast.success('PDF opened! 📄');
        setIsExporting(false);
        return;
      }

      // Generate new PDF
      toast.info('Generating PDF... This may take a moment ⏳');

      // Create a simple PDF using browser's print to PDF
      const printWindow = window.open('', '_blank');
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>${combineDocuments ? 'Combined Documents' : documents[0].title}</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 0;
              padding: 20px;
              background: white;
            }
            .document-section {
              page-break-after: always;
              margin-bottom: 40px;
            }
            .document-title {
              font-size: 24px;
              font-weight: bold;
              color: #1f2937;
              margin-bottom: 10px;
              border-bottom: 3px solid #3b82f6;
              padding-bottom: 10px;
            }
            .document-meta {
              font-size: 14px;
              color: #6b7280;
              margin-bottom: 20px;
            }
            .page-image {
              max-width: 100%;
              height: auto;
              margin: 20px 0;
              border: 1px solid #e5e7eb;
              border-radius: 8px;
            }
            .extracted-text {
              background: #f9fafb;
              padding: 20px;
              border-radius: 8px;
              border-left: 4px solid #3b82f6;
              margin-top: 20px;
              font-size: 14px;
              line-height: 1.6;
              white-space: pre-wrap;
            }
            .tags {
              margin-top: 15px;
            }
            .tag {
              display: inline-block;
              background: #dbeafe;
              color: #1e40af;
              padding: 4px 12px;
              border-radius: 12px;
              font-size: 12px;
              margin-right: 8px;
              margin-bottom: 8px;
            }
            .footer {
              position: fixed;
              bottom: 20px;
              right: 20px;
              font-size: 10px;
              color: #9ca3af;
            }
            @media print {
              .page-break { page-break-before: always; }
            }
          </style>
        </head>
        <body>
      `);

      documents.forEach((doc, docIdx) => {
        if (!includeAllPages && !selectedPages.includes(doc.id)) return;

        printWindow.document.write(`
          <div class="document-section">
            <h1 class="document-title">${doc.title}</h1>
            <div class="document-meta">
              <strong>Created:</strong> ${new Date(doc.created_date).toLocaleDateString()} | 
              <strong>Pages:</strong> ${doc.page_count} | 
              <strong>Type:</strong> ${doc.document_type || 'Other'}
            </div>
        `);

        // Add images
        const imageUrls = doc.processed_image_urls || doc.original_image_urls || [];
        imageUrls.forEach((url, pageIdx) => {
          printWindow.document.write(`
            <div>
              <img src="${url}" class="page-image" alt="Page ${pageIdx + 1}" />
              <p style="text-align: center; color: #6b7280; font-size: 12px;">Page ${pageIdx + 1} of ${imageUrls.length}</p>
            </div>
            ${pageIdx < imageUrls.length - 1 ? '<div class="page-break"></div>' : ''}
          `);
        });

        // Add extracted text if enabled
        if (includeExtractedText && doc.extracted_text) {
          printWindow.document.write(`
            <div class="extracted-text">
              <strong>Extracted Text:</strong><br/><br/>
              ${doc.extracted_text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
            </div>
          `);
        }

        // Add tags
        if (doc.tags && doc.tags.length > 0) {
          printWindow.document.write(`
            <div class="tags">
              <strong>Tags:</strong><br/>
              ${doc.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
            </div>
          `);
        }

        printWindow.document.write('</div>');
      });

      printWindow.document.write(`
          <div class="footer">Generated by Helper33 Workspace | ${new Date().toLocaleDateString()}</div>
        </body>
        </html>
      `);

      printWindow.document.close();
      
      // Trigger print dialog after images load
      setTimeout(() => {
        printWindow.focus();
        printWindow.print();
        toast.success('PDF ready! Use Print dialog to save 📄');
      }, 1000);

    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF');
    } finally {
      setIsExporting(false);
    }
  };

  const togglePageSelection = (docId) => {
    setSelectedPages(prev => 
      prev.includes(docId) 
        ? prev.filter(id => id !== docId)
        : [...prev, docId]
    );
  };

  const selectAllPages = () => {
    if (selectedPages.length === documents.length) {
      setSelectedPages([]);
    } else {
      setSelectedPages(documents.map(d => d.id));
    }
  };

  if (!documents || documents.length === 0) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-lg sm:text-xl">
            <FileText className="w-5 h-5 text-blue-600" />
            Export to PDF
          </DialogTitle>
          <DialogDescription className="text-xs sm:text-sm">
            {documents.length === 1 
              ? `Export "${documents[0].title}" as PDF`
              : `Export ${documents.length} documents (${totalPages} pages total)`
            }
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 sm:space-y-6 py-4">
          
          {/* Quality Settings */}
          <div className="space-y-3 p-3 sm:p-4 bg-blue-50 rounded-lg border border-blue-200">
            <h3 className="font-semibold text-gray-800 flex items-center gap-2 text-sm sm:text-base">
              <Settings className="w-4 h-4 text-blue-600" />
              Export Settings
            </h3>

            {/* PDF Quality */}
            <div>
              <Label className="text-xs sm:text-sm mb-2 block">PDF Quality</Label>
              <div className="grid grid-cols-2 gap-2 sm:gap-3">
                <Button
                  variant={pdfQuality === 'standard' ? 'default' : 'outline'}
                  onClick={() => setPdfQuality('standard')}
                  className={`justify-start touch-manipulation min-h-[44px] ${pdfQuality === 'standard' ? 'bg-blue-600' : ''}`}
                >
                  <FileImage className="w-4 h-4 mr-2" />
                  Standard
                  <Badge variant="outline" className="ml-auto text-xs">Fast</Badge>
                </Button>
                <Button
                  variant={pdfQuality === 'high' ? 'default' : 'outline'}
                  onClick={() => setPdfQuality('high')}
                  className={`justify-start touch-manipulation min-h-[44px] ${pdfQuality === 'high' ? 'bg-blue-600' : ''}`}
                >
                  <Image className="w-4 h-4 mr-2" />
                  High Quality
                  <Badge variant="outline" className="ml-auto text-xs">Larger</Badge>
                </Button>
              </div>
            </div>

            {/* Orientation */}
            <div>
              <Label className="text-xs sm:text-sm mb-2 block">Page Orientation</Label>
              <div className="grid grid-cols-2 gap-2 sm:gap-3">
                <Button
                  variant={orientation === 'portrait' ? 'default' : 'outline'}
                  onClick={() => setOrientation('portrait')}
                  className={`touch-manipulation min-h-[44px] ${orientation === 'portrait' ? 'bg-blue-600' : ''}`}
                >
                  Portrait
                </Button>
                <Button
                  variant={orientation === 'landscape' ? 'default' : 'outline'}
                  onClick={() => setOrientation('landscape')}
                  className={`touch-manipulation min-h-[44px] ${orientation === 'landscape' ? 'bg-blue-600' : ''}`}
                >
                  Landscape
                </Button>
              </div>
            </div>

            {/* Additional Options */}
            <div className="space-y-3">
              <div className="flex items-center justify-between p-2 sm:p-3 bg-white rounded border">
                <Label className="text-xs sm:text-sm">Include extracted text</Label>
                <Switch 
                  checked={includeExtractedText} 
                  onCheckedChange={setIncludeExtractedText}
                />
              </div>

              {documents.length > 1 && (
                <div className="flex items-center justify-between p-2 sm:p-3 bg-white rounded border">
                  <Label className="text-xs sm:text-sm">Combine into single PDF</Label>
                  <Switch 
                    checked={combineDocuments} 
                    onCheckedChange={setCombineDocuments}
                  />
                </div>
              )}
            </div>
          </div>

          {/* Page Selection for Multi-Document Export */}
          {documents.length > 1 && (
            <div className="space-y-3 p-3 sm:p-4 bg-purple-50 rounded-lg border border-purple-200">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold text-gray-800 flex items-center gap-2 text-sm sm:text-base">
                  <Grid className="w-4 h-4 text-purple-600" />
                  Select Documents ({selectedPages.length}/{documents.length})
                </h3>
                <div className="flex items-center gap-2">
                  <Switch 
                    checked={includeAllPages} 
                    onCheckedChange={(checked) => {
                      setIncludeAllPages(checked);
                      if (checked) {
                        setSelectedPages(documents.map(d => d.id));
                      }
                    }}
                  />
                  <Label className="text-xs sm:text-sm">All</Label>
                </div>
              </div>

              {!includeAllPages && (
                <div className="space-y-2 max-h-[250px] overflow-y-auto">
                  {documents.map(doc => (
                    <div
                      key={doc.id}
                      className={`p-2 sm:p-3 bg-white rounded-lg border transition-all ${
                        selectedPages.includes(doc.id) 
                          ? 'border-purple-400 bg-purple-50' 
                          : 'border-gray-200'
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <Checkbox
                          checked={selectedPages.includes(doc.id)}
                          onCheckedChange={() => togglePageSelection(doc.id)}
                          className="flex-shrink-0"
                        />
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-gray-800 text-sm truncate">
                            {doc.title}
                          </p>
                          <p className="text-xs text-gray-500">
                            {doc.page_count} page{doc.page_count !== 1 ? 's' : ''}
                            {doc.tags && doc.tags.length > 0 && (
                              <span className="ml-2">• {doc.tags.slice(0, 2).join(', ')}</span>
                            )}
                          </p>
                        </div>
                        {selectedPages.includes(doc.id) && (
                          <CheckCircle className="w-5 h-5 text-purple-600 flex-shrink-0" />
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Export Summary */}
          <div className="p-3 sm:p-4 bg-green-50 rounded-lg border border-green-200">
            <h4 className="font-semibold text-green-900 mb-2 text-sm sm:text-base">Export Summary</h4>
            <ul className="text-xs sm:text-sm text-green-700 space-y-1">
              <li>• {includeAllPages || selectedPages.length === documents.length 
                ? `${documents.length} document${documents.length !== 1 ? 's' : ''}` 
                : `${selectedPages.length} selected document${selectedPages.length !== 1 ? 's' : ''}`
              }</li>
              <li>• {totalPages} total page{totalPages !== 1 ? 's' : ''}</li>
              <li>• Quality: {pdfQuality === 'standard' ? 'Standard (faster, smaller)' : 'High (slower, larger)'}</li>
              <li>• Orientation: {orientation}</li>
              {includeExtractedText && <li>• Includes OCR text</li>}
              {combineDocuments && documents.length > 1 && <li>• Combined into single PDF</li>}
            </ul>
          </div>
        </div>

        <DialogFooter className="flex-col sm:flex-row gap-2">
          <Button
            onClick={onClose}
            variant="outline"
            className="w-full sm:w-auto touch-manipulation min-h-[44px]"
            disabled={isExporting}
          >
            Cancel
          </Button>
          <Button
            onClick={handleExport}
            disabled={isExporting || (!includeAllPages && selectedPages.length === 0)}
            className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700 touch-manipulation min-h-[44px]"
          >
            {isExporting ? (
              <><Loader2 className="w-4 h-4 animate-spin mr-2" />Generating PDF...</>
            ) : (
              <><Download className="w-4 h-4 mr-2" />Export PDF</>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}