
import React, { useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { motion } from 'framer-motion';
import {
  Shield,
  CheckCircle,
  AlertTriangle,
  XCircle,
  RefreshCw,
  Download,
  TrendingUp,
  Lock,
  Eye,
  Server,
  Key,
  FileWarning,
  Zap,
  Activity,
  Database,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import { toast } from 'sonner';
import SEO from '@/components/SEO';

export default function SecurityAuditReport() {
  const [isRunningAudit, setIsRunningAudit] = useState(false);
  const [showEntityDetails, setShowEntityDetails] = useState(false);

  const { data: user } = useQuery({
    queryKey: ['currentUser'],
    queryFn: () => base44.auth.me()
  });

  const { data: auditHistory = [], refetch: refetchHistory } = useQuery({
    queryKey: ['auditHistory'],
    queryFn: () => base44.entities.SecurityAuditLog.list('-created_date', 10),
    enabled: user?.role === 'admin',
    initialData: []
  });

  const { data: latestAudit, refetch: refetchAudit } = useQuery({
    queryKey: ['latestAudit'],
    queryFn: async () => {
      const audits = await base44.entities.SecurityAuditLog.list('-created_date', 1);
      return audits[0] || null;
    },
    enabled: user?.role === 'admin'
  });

  const runSecurityAudit = async () => {
    setIsRunningAudit(true);
    toast.loading('🔍 Running comprehensive security audit on all 213 entities...', { id: 'audit' });
    
    try {
      const { data: result } = await base44.functions.invoke('runSecurityAudit');
      
      if (result.error) {
        toast.error(`Audit failed: ${result.error}`, { id: 'audit' });
      } else {
        toast.success(`✅ Security audit completed! Score: ${result.score}/${result.max_score}`, { 
          id: 'audit',
          duration: 5000,
          description: `Status: ${result.overall_status.toUpperCase()} • Entities: ${result.entity_security?.total_entities || 0} scanned`
        });
        await refetchAudit();
        await refetchHistory();
      }
    } catch (error) {
      toast.error('Failed to run security audit', { id: 'audit' });
      console.error(error);
    } finally {
      setIsRunningAudit(false);
    }
  };

  // Auto-run audit on first load if no audit exists
  useEffect(() => {
    if (user?.role === 'admin' && !latestAudit && !isRunningAudit && auditHistory.length === 0) {
      toast.info('📊 Running initial security scan...', { duration: 2000 });
      setTimeout(() => {
        runSecurityAudit();
      }, 1000);
    }
  }, [user, latestAudit, isRunningAudit, auditHistory]);

  const exportReport = () => {
    if (!latestAudit) return;
    
    const reportText = `
HELPER33 SECURITY AUDIT REPORT
===============================
Date: ${new Date(latestAudit.audit_date).toLocaleString()}
Auditor: ${latestAudit.auditor_email}
Overall Status: ${latestAudit.overall_status.toUpperCase()}
Security Score: ${latestAudit.score}/${latestAudit.max_score}

ENTITY SECURITY SCAN:
${latestAudit.entity_scan_results ? `
Total Entities: ${latestAudit.entity_scan_results.total_entities}
Secure Entities: ${latestAudit.entity_scan_results.secure_entities}
Vulnerable Entities: ${latestAudit.entity_scan_results.vulnerable_entities}
Missing RLS: ${latestAudit.entity_scan_results.missing_rls_entities}
Public Write Access: ${latestAudit.entity_scan_results.public_write_entities}

Entity Issues:
${latestAudit.entity_scan_results.issues.map((issue, i) => `
${i + 1}. ${issue.entity} (${issue.severity})
   Issue: ${issue.issue}
   Recommendation: ${issue.recommendation}
`).join('\n')}
` : 'No entity scan data available'}

TEST RESULTS:
${latestAudit.test_results.map((test, i) => `
${i + 1}. ${test.test} (${test.category})
   Status: ${test.status.toUpperCase()}
   Severity: ${test.severity.toUpperCase()}
   Score: ${test.score}
   Details: ${test.details}
`).join('\n')}

SUMMARY:
- Total Tests: ${latestAudit.test_results.length}
- Passed: ${latestAudit.test_results.filter(t => t.status === 'pass').length}
- Warnings: ${latestAudit.warnings}
- Critical Failures: ${latestAudit.critical_failures}
- Environment: ${latestAudit.environment.toUpperCase()}

Generated by Helper33 Security System
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security-audit-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Security report downloaded');
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'pass': return 'bg-green-100 text-green-800 border-green-300';
      case 'warning': return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'fail': return 'bg-red-100 text-red-800 border-red-300';
      case 'error': return 'bg-gray-100 text-gray-800 border-gray-300';
      default: return 'bg-gray-100 text-gray-800 border-gray-300';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'pass': return <CheckCircle className="w-5 h-5 text-green-600" />;
      case 'warning': return <AlertTriangle className="w-5 h-5 text-yellow-600" />;
      case 'fail': return <XCircle className="w-5 h-5 text-red-600" />;
      default: return <FileWarning className="w-5 h-5 text-gray-600" />;
    }
  };

  const getCategoryIcon = (category) => {
    const iconMap = {
      'Authentication': Key,
      'Authorization': Lock,
      'Data Privacy': Eye,
      'Secrets Management': Shield,
      'Transport Security': Server,
      'HTTP Security': Zap,
      'Session Security': Activity,
      'API Security': Server,
      'Input Security': FileWarning,
      'Data Security': Lock,
      'Entity Security': Database,
      'Safety Features': Shield
    };
    return iconMap[category] || Shield;
  };

  if (user?.role !== 'admin') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-50 to-orange-50 p-6 flex items-center justify-center">
        <Card className="max-w-md">
          <CardContent className="p-8 text-center">
            <Shield className="w-16 h-16 text-red-500 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-900 mb-2">Access Denied</h2>
            <p className="text-gray-600">This page is only accessible to administrators.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <>
      <SEO
        title="Security Audit Report - Helper33 Admin"
        description="Comprehensive security audit and testing results for Helper33 platform"
      />

      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-purple-50 p-6">
        <div className="max-w-7xl mx-auto">
          
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-8"
          >
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-4">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                  className="w-16 h-16 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center shadow-2xl"
                >
                  <Shield className="w-8 h-8 text-white" />
                </motion.div>
                <div>
                  <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                    🛡️ Security Audit Report
                  </h1>
                  <p className="text-gray-600">Comprehensive security testing • All entities scanned</p>
                </div>
              </div>

              <div className="flex gap-3">
                <Button
                  onClick={exportReport}
                  variant="outline"
                  disabled={!latestAudit}
                  className="gap-2"
                >
                  <Download className="w-4 h-4" />
                  Export
                </Button>
                <Button
                  onClick={runSecurityAudit}
                  disabled={isRunningAudit}
                  className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 gap-2 shadow-xl"
                >
                  {isRunningAudit ? (
                    <RefreshCw className="w-4 h-4 animate-spin" />
                  ) : (
                    <Shield className="w-4 h-4" />
                  )}
                  {isRunningAudit ? 'Scanning...' : 'Run Full Audit'}
                </Button>
              </div>
            </div>

            {/* Quick Summary Banner */}
            {latestAudit && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className={`p-6 rounded-2xl border-4 ${
                  latestAudit.overall_status === 'pass'
                    ? 'bg-gradient-to-r from-green-500 to-emerald-600 border-green-400'
                    : latestAudit.overall_status === 'warning'
                    ? 'bg-gradient-to-r from-yellow-500 to-amber-600 border-yellow-400'
                    : 'bg-gradient-to-r from-red-500 to-rose-600 border-red-400'
                } text-white shadow-2xl mb-6`}
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    {latestAudit.overall_status === 'pass' ? (
                      <CheckCircle className="w-12 h-12" />
                    ) : latestAudit.overall_status === 'warning' ? (
                      <AlertTriangle className="w-12 h-12" />
                    ) : (
                      <XCircle className="w-12 h-12" />
                    )}
                    <div>
                      <h2 className="text-3xl font-bold mb-1">
                        {latestAudit.overall_status === 'pass' ? '✅ Security PASSED' :
                         latestAudit.overall_status === 'warning' ? '⚠️ Review Recommended' :
                         '❌ Action Required'}
                      </h2>
                      <p className="text-white/90">
                        {latestAudit.overall_status === 'pass' 
                          ? '🎉 Your app is secure and ready to publish!'
                          : latestAudit.overall_status === 'warning'
                          ? '⚡ Some improvements recommended before publishing'
                          : '🚨 Critical security issues must be fixed'}
                      </p>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-5xl font-bold mb-1">{latestAudit.score}</div>
                    <div className="text-white/90 text-sm">/ {latestAudit.max_score} points</div>
                  </div>
                </div>
              </motion.div>
            )}
          </motion.div>

          {/* Latest Audit Results */}
          {latestAudit && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="mb-8 space-y-6"
            >
              {/* Stats Overview */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <Card className="border-2 border-blue-300 bg-blue-50">
                  <CardContent className="p-6 text-center">
                    <div className="text-4xl font-bold text-blue-600 mb-2">
                      {latestAudit.test_results.length}
                    </div>
                    <p className="text-sm text-gray-700 font-medium">Total Tests</p>
                  </CardContent>
                </Card>

                <Card className="border-2 border-green-300 bg-green-50">
                  <CardContent className="p-6 text-center">
                    <div className="text-4xl font-bold text-green-600 mb-2">
                      {latestAudit.test_results.filter(t => t.status === 'pass').length}
                    </div>
                    <p className="text-sm text-gray-700 font-medium">Passed</p>
                  </CardContent>
                </Card>

                <Card className="border-2 border-yellow-300 bg-yellow-50">
                  <CardContent className="p-6 text-center">
                    <div className="text-4xl font-bold text-yellow-600 mb-2">
                      {latestAudit.warnings}
                    </div>
                    <p className="text-sm text-gray-700 font-medium">Warnings</p>
                  </CardContent>
                </Card>

                <Card className="border-2 border-red-300 bg-red-50">
                  <CardContent className="p-6 text-center">
                    <div className="text-4xl font-bold text-red-600 mb-2">
                      {latestAudit.critical_failures}
                    </div>
                    <p className="text-sm text-gray-700 font-medium">Critical</p>
                  </CardContent>
                </Card>
              </div>

              {/* Entity Security Summary */}
              {latestAudit.entity_scan_results && (
                <Card className="border-2 border-blue-300 shadow-xl">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <div>
                        <CardTitle className="flex items-center gap-2 text-2xl">
                          <Database className="w-6 h-6 text-blue-600" />
                          📊 Entity Security Scan
                        </CardTitle>
                        <CardDescription>
                          Analyzed {latestAudit.entity_scan_results.total_entities} data entities for RLS and access control
                        </CardDescription>
                      </div>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setShowEntityDetails(!showEntityDetails)}
                      >
                        {showEntityDetails ? (
                          <>
                            Hide Details <ChevronUp className="w-4 h-4 ml-2" />
                          </>
                        ) : (
                          <>
                            Show Details <ChevronDown className="w-4 h-4 ml-2" />
                          </>
                        )}
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
                      <motion.div
                        whileHover={{ scale: 1.05, y: -5 }}
                        className="text-center p-4 bg-gradient-to-br from-blue-100 to-blue-200 rounded-xl shadow-lg border-2 border-blue-300"
                      >
                        <div className="text-4xl font-bold text-blue-600">
                          {latestAudit.entity_scan_results.total_entities}
                        </div>
                        <p className="text-sm text-gray-700 font-medium mt-2">Total Entities</p>
                      </motion.div>
                      <motion.div
                        whileHover={{ scale: 1.05, y: -5 }}
                        className="text-center p-4 bg-gradient-to-br from-green-100 to-green-200 rounded-xl shadow-lg border-2 border-green-300"
                      >
                        <div className="text-4xl font-bold text-green-600">
                          {latestAudit.entity_scan_results.secure_entities}
                        </div>
                        <p className="text-sm text-gray-700 font-medium mt-2">✅ Secure</p>
                      </motion.div>
                      <motion.div
                        whileHover={{ scale: 1.05, y: -5 }}
                        className="text-center p-4 bg-gradient-to-br from-yellow-100 to-yellow-200 rounded-xl shadow-lg border-2 border-yellow-300"
                      >
                        <div className="text-4xl font-bold text-yellow-600">
                          {latestAudit.entity_scan_results.vulnerable_entities}
                        </div>
                        <p className="text-sm text-gray-700 font-medium mt-2">⚠️ Vulnerable</p>
                      </motion.div>
                      <motion.div
                        whileHover={{ scale: 1.05, y: -5 }}
                        className="text-center p-4 bg-gradient-to-br from-orange-100 to-orange-200 rounded-xl shadow-lg border-2 border-orange-300"
                      >
                        <div className="text-4xl font-bold text-orange-600">
                          {latestAudit.entity_scan_results.public_write_entities}
                        </div>
                        <p className="text-sm text-gray-700 font-medium mt-2">📝 Public Write</p>
                      </motion.div>
                      <motion.div
                        whileHover={{ scale: 1.05, y: -5 }}
                        className="text-center p-4 bg-gradient-to-br from-red-100 to-red-200 rounded-xl shadow-lg border-2 border-red-300"
                      >
                        <div className="text-4xl font-bold text-red-600">
                          {latestAudit.entity_scan_results.missing_rls_entities}
                        </div>
                        <p className="text-sm text-gray-700 font-medium mt-2">🚨 Missing RLS</p>
                      </motion.div>
                    </div>

                    {/* Entity Issues Details */}
                    {showEntityDetails && latestAudit.entity_scan_results.issues.length > 0 && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        className="space-y-2 max-h-96 overflow-y-auto"
                      >
                        <h4 className="font-bold text-gray-900 mb-3 flex items-center gap-2">
                          <AlertTriangle className="w-5 h-5 text-yellow-600" />
                          Entity Security Issues ({latestAudit.entity_scan_results.issues.length})
                        </h4>
                        {latestAudit.entity_scan_results.issues.map((issue, idx) => (
                          <motion.div
                            key={idx}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: idx * 0.05 }}
                            className={`p-4 rounded-xl border-2 ${
                              issue.severity === 'critical' ? 'bg-red-50 border-red-300' :
                              issue.severity === 'high' ? 'bg-orange-50 border-orange-300' :
                              issue.severity === 'medium' ? 'bg-yellow-50 border-yellow-300' :
                              'bg-blue-50 border-blue-300'
                            }`}
                          >
                            <div className="flex items-start justify-between">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-2">
                                  <Badge className={getSeverityBadgeColor(issue.severity)}>
                                    {issue.severity.toUpperCase()}
                                  </Badge>
                                  <p className="font-bold text-gray-900">{issue.entity}</p>
                                </div>
                                <p className="text-sm text-gray-700 mb-2">🔍 {issue.issue}</p>
                                <p className="text-xs text-gray-600 bg-white/60 p-2 rounded-lg border border-gray-200">
                                  💡 <strong>Fix:</strong> {issue.recommendation}
                                </p>
                              </div>
                            </div>
                          </motion.div>
                        ))}
                      </motion.div>
                    )}

                    {showEntityDetails && latestAudit.entity_scan_results.issues.length === 0 && (
                      <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="text-center py-12 bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl border-4 border-green-300"
                      >
                        <CheckCircle className="w-20 h-20 mx-auto mb-4 text-green-600" />
                        <p className="text-2xl font-bold text-green-900 mb-2">🎉 Perfect Security!</p>
                        <p className="text-gray-700">All entities have proper RLS configuration and access control</p>
                      </motion.div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Test Results */}
              <div className="grid md:grid-cols-2 gap-6">
                {latestAudit.test_results.map((test, index) => {
                  const CategoryIcon = getCategoryIcon(test.category);
                  
                  return (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: index * 0.05 }}
                      whileHover={{ scale: 1.02, y: -5 }}
                    >
                      <Card className={`border-3 ${getStatusColor(test.status)} hover:shadow-2xl transition-all`}>
                        <CardHeader className="pb-3">
                          <div className="flex items-start justify-between">
                            <div className="flex items-center gap-3">
                              <div className={`p-3 rounded-xl ${
                                test.status === 'pass' ? 'bg-green-100' :
                                test.status === 'warning' ? 'bg-yellow-100' :
                                'bg-red-100'
                              } shadow-lg`}>
                                <CategoryIcon className="w-6 h-6" />
                              </div>
                              <div>
                                <CardTitle className="text-base">{test.test}</CardTitle>
                                <CardDescription className="text-xs">{test.category}</CardDescription>
                              </div>
                            </div>
                            <motion.div
                              animate={{ scale: [1, 1.2, 1] }}
                              transition={{ duration: 2, repeat: Infinity }}
                            >
                              {getStatusIcon(test.status)}
                            </motion.div>
                          </div>
                        </CardHeader>
                        <CardContent>
                          <p className="text-sm text-gray-700 mb-3 bg-white/60 p-3 rounded-lg">{test.details}</p>
                          <div className="flex items-center justify-between">
                            <Badge className={`${getSeverityColor(test.severity)} text-xs px-3 py-1`}>
                              {test.severity.toUpperCase()}
                            </Badge>
                            <span className="text-lg font-bold text-gray-900">
                              {test.score} pts
                            </span>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  );
                })}
              </div>

              {/* Publishing Recommendation */}
              {latestAudit.overall_status === 'pass' && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.5 }}
                >
                  <Card className="bg-gradient-to-br from-green-100 to-emerald-100 border-4 border-green-400 shadow-2xl">
                    <CardContent className="p-8">
                      <div className="text-center">
                        <motion.div
                          animate={{ 
                            rotate: [0, 10, -10, 0],
                            scale: [1, 1.1, 1]
                          }}
                          transition={{ duration: 2, repeat: Infinity }}
                        >
                          <CheckCircle className="w-24 h-24 text-green-600 mx-auto mb-4" />
                        </motion.div>
                        <h2 className="text-3xl font-bold text-green-900 mb-3">
                          ✅ Ready to Publish!
                        </h2>
                        <p className="text-green-800 mb-6 max-w-2xl mx-auto text-lg">
                          Your application passed all security checks with a score of <strong>{latestAudit.score}/{latestAudit.max_score}</strong>.
                          All {latestAudit.entity_scan_results?.total_entities || 0} entities have been scanned and secured.
                        </p>
                        <div className="flex gap-4 justify-center">
                          <Button
                            onClick={exportReport}
                            size="lg"
                            className="bg-white text-green-700 hover:bg-green-50 border-2 border-green-400 shadow-lg"
                          >
                            <Download className="w-5 h-5 mr-2" />
                            Download Security Certificate
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )}

              {/* Action Required */}
              {latestAudit.overall_status !== 'pass' && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.5 }}
                >
                  <Card className={`border-4 ${
                    latestAudit.overall_status === 'warning' 
                      ? 'border-yellow-400 bg-gradient-to-br from-yellow-50 to-amber-50'
                      : 'border-red-400 bg-gradient-to-br from-red-50 to-rose-50'
                  } shadow-2xl`}>
                    <CardContent className="p-8">
                      <div className="text-center">
                        {latestAudit.overall_status === 'warning' ? (
                          <AlertTriangle className="w-20 h-20 text-yellow-600 mx-auto mb-4" />
                        ) : (
                          <XCircle className="w-20 h-20 text-red-600 mx-auto mb-4" />
                        )}
                        <h2 className="text-2xl font-bold text-gray-900 mb-3">
                          {latestAudit.overall_status === 'warning' 
                            ? '⚠️ Review Security Issues'
                            : '🚨 Critical Security Issues Found'}
                        </h2>
                        <p className={`mb-6 max-w-2xl mx-auto ${
                          latestAudit.overall_status === 'warning' ? 'text-yellow-900' : 'text-red-900'
                        }`}>
                          {latestAudit.overall_status === 'warning'
                            ? `Found ${latestAudit.warnings} warnings and ${latestAudit.entity_scan_results?.vulnerable_entities || 0} vulnerable entities. Review recommended before publishing.`
                            : `Found ${latestAudit.critical_failures} critical issues and ${latestAudit.entity_scan_results?.vulnerable_entities || 0} vulnerable entities. Fix these before publishing.`}
                        </p>
                        <p className="text-sm text-gray-700 bg-white/80 p-4 rounded-lg border-2 border-gray-300 max-w-lg mx-auto">
                          📋 Review the detailed issues above and apply the recommended fixes.
                          Re-run the audit after making changes.
                        </p>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )}
            </motion.div>
          )}

          {/* No Audit Yet */}
          {!latestAudit && !isRunningAudit && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <Card className="border-2 border-dashed border-blue-300 shadow-xl">
                <CardContent className="p-12 text-center">
                  <motion.div
                    animate={{ 
                      scale: [1, 1.1, 1],
                      rotate: [0, 5, -5, 0]
                    }}
                    transition={{ duration: 3, repeat: Infinity }}
                  >
                    <Shield className="w-24 h-24 text-blue-400 mx-auto mb-6" />
                  </motion.div>
                  <h3 className="text-3xl font-bold text-gray-900 mb-3">🔐 Run Your First Security Audit</h3>
                  <p className="text-gray-600 mb-8 max-w-xl mx-auto text-lg">
                    Scan all entities, test authentication, check encryption, and get a comprehensive security report
                  </p>
                  <Button
                    onClick={runSecurityAudit}
                    size="lg"
                    className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 shadow-2xl px-12 py-6 text-lg"
                  >
                    <Shield className="w-6 h-6 mr-3" />
                    Run Security Audit Now
                  </Button>
                  <p className="text-sm text-gray-500 mt-4">
                    ⏱️ Takes about 5-10 seconds to complete
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Audit History */}
          {auditHistory.length > 1 && ( // Changed from > 0 to > 1 to exclude latest audit which is shown above
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="mt-8"
            >
              <Card className="border-2 border-purple-300 shadow-xl">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <TrendingUp className="w-5 h-5 text-purple-600" />
                    📈 Audit History
                  </CardTitle>
                  <CardDescription>Previous security audits and trend analysis</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {auditHistory.slice(1).map((audit) => ( // Sliced to exclude the latest audit
                      <motion.div
                        key={audit.id}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        whileHover={{ scale: 1.02, x: 5 }}
                        className={`p-4 rounded-xl border-2 ${getStatusColor(audit.overall_status)} flex items-center justify-between shadow-md`}
                      >
                        <div className="flex items-center gap-4">
                          {getStatusIcon(audit.overall_status)}
                          <div>
                            <p className="font-semibold text-gray-900">
                              📅 {new Date(audit.audit_date).toLocaleDateString()} at {new Date(audit.audit_date).toLocaleTimeString()}
                            </p>
                            <p className="text-sm text-gray-600">
                              Score: {audit.score}/{audit.max_score} • {audit.test_results.length} tests
                              {audit.entity_scan_results && ` • ${audit.entity_scan_results.total_entities} entities scanned`}
                            </p>
                          </div>
                        </div>
                        <div className="text-right">
                          <Badge className="bg-blue-100 text-blue-800 mb-1">
                            {audit.environment}
                          </Badge>
                          <p className="text-xs text-gray-600">{audit.auditor_email}</p>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Security Best Practices */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="mt-8"
          >
            <Card className="bg-gradient-to-br from-blue-50 to-purple-50 border-2 border-blue-300 shadow-xl">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Shield className="w-6 h-6 text-blue-600" />
                  🔒 Security Best Practices Active
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid md:grid-cols-2 gap-6">
                  {[
                    { icon: Lock, title: 'End-to-End Encryption', desc: 'All user data encrypted in transit and at rest' },
                    { icon: Eye, title: 'Row-Level Security', desc: 'Users can only access their own data' },
                    { icon: Key, title: 'JWT Authentication', desc: 'Secure token-based user authentication' },
                    { icon: Server, title: 'HTTPS Enforcement', desc: 'All traffic encrypted with TLS 1.3' },
                    { icon: Database, title: 'Automated Backups', desc: 'Daily encrypted backups with 99.9% uptime' },
                    { icon: Zap, title: 'Rate Limiting', desc: 'API abuse prevention and DDoS protection' }
                  ].map((item, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: idx * 0.1 }}
                      className="flex gap-3"
                    >
                      <div className="p-2 rounded-lg bg-gradient-to-br from-blue-100 to-purple-100 h-fit">
                        <item.icon className="w-5 h-5 text-blue-600" />
                      </div>
                      <div>
                        <p className="font-semibold text-gray-900 mb-1">{item.title}</p>
                        <p className="text-sm text-gray-600">{item.desc}</p>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </div>
    </>
  );
}

function getSeverityColor(severity) {
  switch (severity) {
    case 'critical': return 'bg-red-100 text-red-800 border-red-300';
    case 'high': return 'bg-orange-100 text-orange-800 border-orange-300';
    case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-300';
    case 'low': return 'bg-blue-100 text-blue-800 border-blue-300';
    default: return 'bg-gray-100 text-gray-800 border-gray-300';
  }
}

function getSeverityBadgeColor(severity) {
  switch (severity) {
    case 'critical': return 'bg-red-600 text-white';
    case 'high': return 'bg-orange-600 text-white';
    case 'medium': return 'bg-yellow-600 text-white';
    case 'low': return 'bg-blue-600 text-white';
    default: return 'bg-gray-600 text-white';
  }
}
